stealing_clothes = {'name':'Guild Mission','desc':'Caught stealing the thanes fine clothes for brynjolf', 'effect':'Jail, Do not pass go, do not collect $200'}
bribe_informant = {'name':'Guild Mission','desc':'Bribe an informant', 'effect':'Pay $500'}
adventure_tax = {'name':'Guild Mission','desc':'Adventurer tax', 'effect':'Pay $250'}
accidently_killed_chicken = {'name':'Guild Mission','desc':'Accidently killed a chicken during an assassination', 'effect':'Jail, Do not pass go, do not coll $200'}
looted_silver = {'name':'Guild Mission','desc':'Looted silver hand camp', 'effect':'You get $500'}
lollygagging = {'name':'Guild Mission','desc':'Lollygagging fine', 'effect':'Pay $1000'}
lockpick = {'name':'Guild Mission','desc':'Lockpick, use to get out of jail free', 'effect':'Get out of jail free'}
arrow_knee = {'name':'Guild Mission','desc':'Took an arrow to the knee', 'effect':'Miss your next turn'}
draugr_sword = {'name':'Guild Mission','desc':'Recovered ancient draugr sword', 'effect':'You get $250'}
won_tournament = {'name':'Guild Mission','desc':'You won guild tournament', 'effect':'Collect $250 from each player'}
private_fire = {'name':'Guild Mission','desc':'A Guild member sets fire to your private quarters', 'effect':'Pay $150/house, $500/hotel'}
captive_guild = {'name':'Guild Mission','desc':'Rescued captive guild member', 'effect':'You get $250'}
guild_leader = {'name':'Guild Mission','desc':'Promoted to guild leader', 'effect':'Move to any space'}